Add meetup data for June 2021
RubyNepal/rubynepal.github.io pull request #574
Opened 2021-06-20 12:08 UTC by josisusan

Meetup link: https://www.meetup.com/Nepal-Ruby-Users-Group/events/278772412/
Talk Title: Beginner's Guide to building API using Ruby on Rails

Speakers:

1. Abhinav Risal
Senior Software Engineer
Bajra Technologies
https://www.linkedin.com/in/arisal2/

2. Roman KC
Software Engineer
Bajra Technologies
https://www.linkedin.com/in/kcromanpl/

Time: June 19, 2021 02:00 PM Online

2021-06-20 12:10 UTC, josisusan commented
Youtube link will be added after it has been published publicly.

2021-06-21 04:54 UTC, zoras requested changes

2021-06-21 04:54 UTC, zoras commented on js/meetup/data.js
> +        title: "Beginner's Guide to building API using Ruby on Rails",
Let's change this title as `Beginner's Guide to building API using Ruby on Rails (Live Demo)`

2021-06-21 05:22 UTC, zoras approved these changes
LGTM 🚀

2021-06-21 05:22 UTC, merged